%{
Returns alanine spectrum generated by Spinach with the specified 
coupling matrix
%}

function [contour_spec, axis_f1, axis_f2] = simAlanine(coupling_matrix, plot)

% System setup
sys.isotopes = {'13C','13C','13C'};
sys.magnet = 25.83793; 

parameters.spins = {'13C'};
parameters.offset = 27666.0596999818;
parameters.sweep = [99607.774701492 49999.9999999999];
parameters.npoints = [2048 4096];
parameters.zerofill = [4096 16384];
parameters.axis_units = 'ppm';
parameters.J = 50;

% Parameters for plotting
parameters_plot = parameters;
parameters_plot.offset = [27666.0596999818*2 27666.0596999818];

% Basis set
bas.formalism = 'sphten-liouv';
bas.approximation = 'none';

% --- Interaction Setup ---
inter.zeeman.scalar = {178.3 53.02 18.62}; % {177.89 52.86 18.62};  
inter.coupling.scalar = num2cell(coupling_matrix);
inter.temperature = 300;

% --- Spinach Setup ---
spin_system = create(sys, inter);
spin_system.sys.output = 'hush';
spin_system = basis(spin_system, bas);

% Output prealloc
spectrum = zeros(parameters.zerofill(2), parameters.zerofill(1));

fid = liquid(spin_system, @inadequate_2d, parameters, 'nmr');

% Apodization
fid.cos = apodisation(spin_system, fid.cos, {{'cos'}, {'cos'}});
fid.sin = apodisation(spin_system, fid.sin, {{'cos'}, {'cos'}});

spec_cos = fftshift(fft(fid.cos, parameters.zerofill(2), 1), 1);
spec_sin = fftshift(fft(fid.sin, parameters.zerofill(2), 1), 1);
spec_states = real(spec_cos) + 1i * real(spec_sin);
spectrum = fftshift(fft(spec_states, parameters.zerofill(1), 2), 2);

% Normalize
alanine_spec = abs(spectrum) / max(abs(spectrum(:)));
%alanine_spec = alanine_spec.';
contour_spec = abs(alanine_spec).'; 

% 1. Get Axes using plot_2d (invisible figure)
fig = figure('Visible','off');
[axis_f1, axis_f2, ~] = plot_2d(spin_system, real(alanine_spec), parameters_plot, ...
     20, [0.01 0.5 0.01 0.5], 2, 256, 6, 'positive');
close(fig);

% --- Plotting ---
if plot

    % 2. Manual Contour Plot
    figure();
    
    [M, c] = contour(axis_f2, axis_f1, contour_spec, 40);
    c.LineColor = 'b';
    
    % Formatting
    set(gca, 'XDir', 'reverse', 'YDir', 'reverse');
    xlabel('F2: 13C chemical shift / ppm');
    ylabel('F1: DQ dimension / ppm');
    % title('INADEQUATE: Alanine Simulation');
    % grid on;
    
    hold on;
end

end